name: seven.yaml
on:
  push
permissions:
  contents: write
jobs:
  seven-build:
    if: "contains(github.event.head_commit.message, '06')"
    name: 07 build å·¥ä½œ
    runs-on: ubuntu-latest
    steps:
      - name: è¯»å–ä»“åº“å†…å®¹
        uses: actions/checkout@v4
      - name: å®‰è£…ä¾èµ–å’Œæ„å»º
        run: |
          cd 07-practice
          npm install
          npm run build
      - name: éƒ¨ç½² ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: 07-build
          folder: 07-build
